name: _gAuto-CryoVer inspired by Master Jayharron Abejar

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

permissions:
  contents: write  # allow pushing commits

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README commit count and timestamp
        run: |
          FILE="README.md"

          if [ ! -f "$FILE" ]; then
            echo "# GitHub Auto Commit Project" > "$FILE"
            echo "" >> "$FILE"
            echo "This repository demonstrates an **hourly automated commit** using GitHub Actions." >> "$FILE"
            echo "It automatically updates this README to keep track of how many commits have been made by the bot." >> "$FILE"
            echo "" >> "$FILE"
            echo "💡 **Inspired by:** Master Jayharron Abejar — I am truly grateful for his guidance and inspiration." >> "$FILE"
            echo "" >> "$FILE"
            echo "---" >> "$FILE"
            echo "" >> "$FILE"
            echo "## Commits" >> "$FILE"
            echo "commit number: 0" >> "$FILE"
            echo "Last updated: Never" >> "$FILE"
          fi

          CURRENT=$(grep -oP '(?<=commit number: )\d+' "$FILE" || echo "0")
          NEXT=$((CURRENT + 1))
          NOW=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          sed -i "s/commit number: $CURRENT/commit number: $NEXT/" "$FILE"

          if grep -q "Last updated:" "$FILE"; then
            sed -i "s|Last updated: .*|Last updated: $NOW|" "$FILE"
          else
            echo "Last updated: $NOW" >> "$FILE"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated commit #$NEXT" || echo "No changes to commit"
          git push
